### ISSUE TITLE
cysignals-CSI fails on Py3

### ISSUE THREAD

**Issue by anntzer** [sagemath/cysignals#32]
Minimal segfaulting extension module:

```
include "cysignals/signals.pxi"
def segfault():
    cdef int* p = NULL
    p[0] = 42
```

Build and run (note: python = python3)

```
$ python setup.py build_ext -i && python -c 'import foo; foo.segfault()'
```

results in the following traceback

```
------------------------------------------------------------------------
/usr/lib/python3.5/site-packages/cysignals/signals.cpython-35m-x86_64-linux-gnu.so(+0x42f7)[0x7fe60eda52f7]
/usr/lib/python3.5/site-packages/cysignals/signals.cpython-35m-x86_64-linux-gnu.so(+0x46e5)[0x7fe60eda56e5]
/usr/lib/python3.5/site-packages/cysignals/signals.cpython-35m-x86_64-linux-gnu.so(+0x6e17)[0x7fe60eda7e17]
/usr/lib/libpthread.so.0(+0x10f00)[0x7fe610067f00]
/tmp/foo/foo.cpython-35m-x86_64-linux-gnu.so(+0x1510)[0x7fe60efb3510]
/usr/lib/libpython3.5m.so.1.0(PyEval_EvalFrameEx+0x843c)[0x7fe61039b1bc]
/usr/lib/libpython3.5m.so.1.0(+0x1282c3)[0x7fe61039c2c3]
/usr/lib/libpython3.5m.so.1.0(PyEval_EvalCodeEx+0x23)[0x7fe61039c3a3]
/usr/lib/libpython3.5m.so.1.0(PyEval_EvalCode+0x1b)[0x7fe61039c3cb]
/usr/lib/libpython3.5m.so.1.0(+0x147364)[0x7fe6103bb364]
/usr/lib/libpython3.5m.so.1.0(PyRun_StringFlags+0x75)[0x7fe6103bcd35]
/usr/lib/libpython3.5m.so.1.0(PyRun_SimpleStringFlags+0x3b)[0x7fe6103bcd9b]
/usr/lib/libpython3.5m.so.1.0(Py_Main+0x7c7)[0x7fe6103d3f87]
python(main+0x170)[0x400af0]
/usr/lib/libc.so.6(__libc_start_main+0xf1)[0x7fe60fcd6741]
python(_start+0x29)[0x400b99]
------------------------------------------------------------------------
Attaching gdb to process id 10048.
Traceback (most recent call last):
  File "/usr/bin/cysignals-CSI", line 187, in <module>
    trace = run_gdb(args.pid, not args.nocolor)
  File "/usr/bin/cysignals-CSI", line 100, in run_gdb
    stdout, stderr = cmd.communicate(gdb_commands(pid, color))
  File "/usr/lib/python3.5/subprocess.py", line 1072, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.5/subprocess.py", line 1700, in _communicate
    input_view = memoryview(self._input)
TypeError: memoryview: a bytes-like object is required, not 'str'
------------------------------------------------------------------------
Unhandled SIGSEGV: A segmentation fault occurred.
This probably occurred because a *compiled* module has a bug
in it and is not properly wrapped with sig_on(), sig_off().
Python will now terminate.
------------------------------------------------------------------------
[1]    10048 segmentation fault (core dumped)  python -c 'import foo; foo.segfault()'
```

This can trivially be fixed by passing `universal_newlines=True` to the `Popen` constructor in `cysignals-CSI` but then another bytes/str confusion occurs a few lines later.

**Comment by anntzer** [comment]
I fixed all the bytes/str issues, but things the fail when the SAGE_SRC environment variable is not defined (because I don't use Sage...).

The following traceback gets printed
```
Traceback (most recent call last):
  File "<string>", line 51, in <module>
  File "<string>", line 40, in cython_debug_files
  File "/usr/lib/python3.5/os.py", line 725, in __getitem__
    raise KeyError(key) from None
KeyError: 'SAGE_SRC'
```
which doesn't seem particularly helpful.

**Comment by kiwifb** [comment]
Yes, that's not helpful. I am not sure what would be a generic way to tell the debugger where to find the cython debug information. That's what that variable is for:
```
def cython_debug_files():
    """
    Cython extra debug information files
    """
    pattern = os.path.join(os.environ['SAGE_SRC'], 'cython_debug',
                           'cython_debug_info_*')
    return glob.glob(pattern)
```
finding the root location of the cython debug files. That also means that I would need to patch cysignals in sage-on-gentoo.

**Comment by anntzer** [comment]
Actually I'm not sure what this is even supposed to do... anything related to https://docs.python.org/3/library/faulthandler.html?
Currently I'm just patching this out in the Arch Linux PKGBUILD: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-cysignals

**Comment by malb** [comment]
Sorry for the lack of reply, I'm struggling with finding time to look at this proper!

**Comment by jdemeyer** [comment]
Not yet fixed, but some progress has been made, see #52. Please continue the discussion there.
